export const REQUESTED_SHEET = 'REQUESTED_SHEET';
export const RECEIVED_SHEET = 'RECEIVED_SHEET';
export const SHEET_FAILED = 'SHEET_FAILED';

export const SET_CELL_VALUES = 'SET_CELL_VALUES';
export const SET_ASYNC_CELL_VALUE = 'SET_ASYNC_CELL_VALUE';
