export const REQUESTED_APP_MODEL= 'REQUESTED_APP_MODEL';
export const RECEIVED_APP_MODEL = 'RECEIVED_APP_MODEL';
export const APP_MODEL_FAILED = 'APP_MODEL_FAILED';

export const SET_CELL_VALUES = 'SET_CELL_VALUES';
export const SET_ASYNC_CELL_VALUE = 'SET_ASYNC_CELL_VALUE';
